name: Run Vitest on Push

on:
  push:
    # branches 分支
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # 你可以根據自己環境調整 node 版本

      - name: Run ESLint
        run: npm run lint

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest tests
        run: npx vitest run --coverage # 執行測試並輸出 coverage
